//
// Copyright (c) 2020 NVI, Inc.
//
// This file is part of the FSL10 Linux distribution.
// (see http://github.com/nvi-inc/fsl10).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= DRAFT telegraf installation for KPGO 12m FS computers
E. Himwich, C. Frock, C. Coughlin
Version 0.3 - October 2020

:sectnums:

:toc:
== Introduction

This document lays out the plan for installing `telegraf` (a collector
for the MAS) for the KPGO 12m Field System computers.  The resulting
configuration will be the same as is used at MGO.  `Telegraf` should
be installed on both *fs1* and *fs2*. The one on *fs1* is the nominal
operational installation. The one on *fs2* is there in case operations
have to move to the *fs2* disks. It should be disabled on *fs2* until
it is needed.

The installation process uses the "Recoverable test" procedure of
FSL10 to enable easy recovery in case of a problem. This has the
advantage that if (i) steps are missing from the procedure or (ii)
errors occur, and either or both can't be recovered from directly, it
is relatively easy to return to the original state and start over.

== fs1 installation

All work in this section is to be performed on the KPGO 12m *fs1*
computer.

=== Preparing fs1

. Follow the directions for the recoverable test procedure at:

+
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing
+
[NOTE]
====
If the systems at KPGO have not had the *drop_primary* script
installed yet, use the following command in its place:

    mdadm /dev/md0 -f /dev/sda2
====

. Once the primary disk has been dropped from the RAID, move onto the
next section.

[IMPORTANT]
====
If it is not possible finish the installation before the
next operational use of the system or disk rotation, follow the
*failed* branch of the procedure to return to the previous system
configuration. It will require several hours for the refresh operation
to complete. The system can be used for operations, but not a disk
rotation, while the refresh is in progress. Later, the installation
can be tried again from scratch when it is convenient.

Depending on where in the process the decision to revert the
installation is made, it may necessary to move the MET4A and wind
sensor serial connectors back to *fs1* as well.
====

=== Installing telegraf on fs1

. Remove any previous installation of `telegraf`.

. As `prog`:

.. Create the local configuration directory:

+
   cd /usr2/st
   mkdir telegraf.conf

.. Place the `README` file, listed in <<Appendix A. README file>>, in the directory.

.. Place the `telefgraf.conf` file, listed in <<Appendix B. telegraf.conf>>, in the directory.

. As `root` (cut-and-paste will work for the wrapped second line):

    cd ~
    wget https://github.com/nvi-inc/telegraf/releases/download/v1.14.2-vlbi-0.5.2/telegraf-vlbi_1.14.2.vlbi.0.5.2-1_amd64.deb
    dpkg -i telegraf-vlbi_1.14.2.vlbi.0.5.2-1_amd64.deb
    cp /usr2/st/telegraf/telegraf.conf /etc/telegraf
    systemctl restart telegraf
+
NOTE: The configuration file is already set with the correct alias, `12m`, for
the 12m antenna. The `metserver` host is also properly set as `127.0.0.1`, the local host.

=== Testing telegraf on fs1

. Verify that there are no errors for communication with the antenna by the FS and the ACI program.
+
If there are errors, disable `telegraf` antenna access, as `root`:
+
.. Edit `/etc/telegraf.conf` and comment out the block:
+

    [[inputs.modbus_antenna]]
    ## modbus antenna controller type
    antenna_type = "intertronics12m"
    ## network address in form ip:port
    address = "12m:502"
+
.. Execute:
+

    systemctl restart telegraf


. Verify there are no other problems:

.. Check in `grafana` on the MAS to see if the antenna (if access wasn't already disabled) and met. data are updating.
+
.. A minimal test with the FS to assure that things are working would include:

+

... A quick pointing check, which should not be abnormal and should not have communication errors with the antenna.

+

... Using the `wx` command to verify met data is still available.

== fs2 installation

Once *fs1* has been successfully set-up, the *fs2* disks, running in
the spare computer, can be set-up.  Do not proceed with this step until
`telegraf` is working on *fs1*.

=== Preparing fs2

Follow the instructions in in the <<Preparing fs1>> section above, but this time doing them on *fs2*.

=== Changes needed before installing telegraf on fs2

For this part of the installation it will be necessary to take some additional steps:

. Terminate the FS on *fs1*.
. Stop `telegraf`, `metclient`, and `metserver` on *fs1*, as `root`:

    systemctl stop telegraf
    systemctl stop metclient
    systemctl stop metserver

. Move the serial connectors for the MET4A and wind sensors to the corresponding connectors on *fs2*.

. Start `metserver` on *fs2*, as `root`:

+

    systemctl start metserver

. As `oper`, start the FS on *fs2* and verify that met data is being received with the command:

+
    wx

=== Installing telegraf on fs2

Follow the directions in the <<Installing telegraf on fs1>> section above, but this time performing the steps on *fs2*.

=== Testing telegraf on fs2

Follow the directions in the <<Testing telegraf on fs1>> section above, but this time using *fs2*.

NOTE: If `telegraf` antenna access had to be disabled on *fs1* to eliminate communication errors, it is expected that this will be needed on *fs2* as well.

== Finishing up

The sections covers the steps to follow once `telegraf` has been tested successfully on _both_ *fs1* and *fs2*

=== Finalizing fs2

. Terminate the FS on *fs2*.
. Stop `telegraf` and `metserver` on *fs2*, as `root`:

    systemctl stop telegraf
    systemctl stop metserver

. Disable `telegraf` on *fs2*, as `root`:

    systemctl disable telegraf

. Follow the *successful* steps in the recoverable test procedure:

+
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing

=== Finalizing fs1

. Move the serial connectors for the MET4A and wind sensors to the original connectors on *fs1*.
. Start `metserver`, `telegraf` and `metclient` on *fs1*, as `root`:

    systemctl start metserver
    systemctl start telegraf
    systemctl start metclient

. Start the FS on *fs1*.
. Repeat the second step (Verify there are no other problems) in <<Testing telegraf on fs1>>
. If everything is still working, follow the *successful* steps in the recoverable test procedure:

+
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing

== Appendix A. README file

....
install:

  root:
    cd ~
    wget https://github.com/nvi-inc/telegraf/releases/download/v1.14.2-vlbi-0.5.2/telegraf-vlbi_1.14.2.vlbi.0.5.2-1_amd64.deb
    dpkg -i telegraf-vlbi_1.14.2.vlbi.0.5.2-1_amd64.deb
    cp /usr2/st/telegraf.conf/telegraf.conf /etc/telegraf
      (you may need to change which FS version is pinned)
    systemctl restart telegraf
....

== Appendix B. telegraf.conf

....
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})


# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"


# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  # debug = true
  debug = false
  ## Log only error level messages.
  quiet = false

  ## Log file name, the empty string means to log to stderr.
  #logfile = "/tmp/telegraf.log"
  logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


# Send telegraf metrics to file(s)
#[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  # files = ["/tmp/metrics.out"]

  ## The file will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.
  # rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # rotation_max_archives = 5

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  # data_format = "influx"

# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  # urls = ["udp://127.0.0.1:8089"]
  urls = ["http://mas:8086"]

  ## The target database for metrics; will be created as needed.
  database = "ops"

  ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
  ## Telegraf with a user without permissions to create databases or when the
  ## database already exists.
  skip_database_creation = true

  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.  Only takes effect when using HTTP.
  # retention_policy = ""

  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all".
  ## Only takes effect when using HTTP.
  # write_consistency = "any"

  ## Timeout for HTTP messages.
  # timeout = "5s"

  ## HTTP Basic Auth
  # dummy values
  # username = "something"
  # password = "something_else"
    username = "something"
    password = "something_else"

  ## HTTP User-Agent
  # user_agent = "telegraf"

  ## UDP payload size is the maximum packet size to send.
  # udp_payload = "512B"

  ## Optional TLS Config for use on HTTP connections.
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## HTTP Proxy override, if unset values the standard proxy environment
  ## variables are consulted to determine which proxy, if any, should be used.
  # http_proxy = "http://corporate.proxy:3128"

  ## Additional HTTP headers
  # http_headers = {"X-Special-Header" = "Special-Value"}

  ## HTTP Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
  # content_encoding = "identity"

  ## When true, Telegraf will output unsigned integers as unsigned values,
  ## i.e.: "42u".  You will need a version of InfluxDB supporting unsigned
  ## integer values.  Enabling this option will result in field type errors if
  ## existing data has been written.
  # influx_uint_support = false


###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Read metrics about disk usage
[[inputs.disk]]

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = false


# Query Delphin data logger configured from MGO
[[inputs.delphin_datalogger]]
# Address and port of datalogger modbus port
address = "datalog"
port = 502
timeout = "20s"
slave_id = 1


# Read metrics about memory usage
[[inputs.mem]]
  # no configuration


# Query an antenna controller using modbus over TCP. Registers are assumed to be 32bits wide.
[[inputs.modbus_antenna]]
## modbus antenna controller type
antenna_type = "intertronics12m"
## network address in form ip:port
address = "12m:502"

# Query at MET4 meteorological measurement systems via metserver
[[inputs.met4]]
  ## Address of metserver
  address = "127.0.0.1:50001"
  ## You can add extra tags, for example
  # [inputs.met4.tags]
  #     location = "..."
  #     device = "old"


###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################


# Poll the Field System state through shared memory.
[[inputs.fieldsystem]]
## Poll the Field System state through shared memory.
##
## Record RDBE Tsys and Pcal calculated by FS.
## This complements the rdbe_multicast input.
rdbe = true
## Rate to poll FS variables.
#precision = "100ms"
version = "10.0.0-beta1"
....
