//
// Copyright (c) 2020 NVI, Inc.
//
// This file is part of the FSL10 Linux distribution.
// (see http://github.com/nvi-inc/fsl10).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

= DRAFT telegraf installation for KPGO 12m FS computers
E. Himwich, C. Frock, C. Coughlin
Version 0.5 - October 2020

:sectnums:

:toc:
== Introduction

This document lays out the plan for installing `telegraf` (a collector
for the MAS) for the KPGO 12m Field System computers.  The resulting
configuration will be the same as is used at MGO.  `Telegraf` should
be installed on both *fs1* and *fs2*. The one on *fs1* is the nominal
operational installation. The one on *fs2* is there in case operations
have to move to the *fs2* disks. It should be disabled on *fs2* until
it is needed.

The installation process uses the "Recoverable test" procedure of
FSL10 to enable easy recovery in case of a problem. This has the
advantage that if (i) steps are missing from the procedure or (ii)
errors occur, and either or both can't be recovered from directly, it
is relatively easy to return to the original state and start over.

== Disabling data logger access from the MAS

The `telegraf` installation on the FS computers will query the data
logger. However, the `telegraf` on the MAS computer is already
accessing the data logger.  This will need to be disabled on the MAS
computer to avoid a conflict.  To disable accessing the data logger on
the MAS computer, comment out the data logger lines in the `telegraf`
configuration file on the MAS computer and restart `telegraf` there.

If the installation needs to be reverted (see more details in section
<<Preparing fs1>> below) you will need to re-enable data logger
access on the MAS computer to return to the previous configuration. To
do this, uncomment the relevant lines in the `telegraf` configuration
file on the MAS computer and restart `telegraf` there.

== fs1 installation

All work in this section is to be performed on the KPGO 12m *fs1*
computer.

=== Preparing fs1

. Follow the directions for the recoverable test procedure at:

+
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing
+
[NOTE]
====
If the systems at KPGO have not had the *drop_primary* script
installed yet, use the following command in its place:

    mdadm /dev/md0 -f /dev/sda2
====

. Once the primary disk has been dropped from the RAID, move onto the
next section.

[IMPORTANT]
====
If it is not possible finish the installation before the
next operational use of the system or disk rotation, follow the
*failed* branch of the procedure to return to the previous system
configuration. It will require several hours for the refresh operation
to complete. The system can be used for operations, but not a disk
rotation, while the refresh is in progress. Later, the installation
can be tried again from scratch when it is convenient.

Depending on where in the process the decision to revert the
installation is made, it may necessary to move the MET4A and wind
sensor serial connectors back to *fs1* as well.

When reverting the installation, you may also need to re-enable the
data logger access on MAS, as described in section
<<Disabling data logger access from the MAS>> above.

====

=== Installing telegraf on fs1

. Remove any previous installation of `telegraf`.

. As `prog`:

.. Create the local configuration directory:

+
   cd /usr2/st
   mkdir telegraf.conf

.. Place the `README` and `telefgraf.conf` files in the directory.

. As `root` (cut-and-paste will work for the wrapped second line):
+
[NOTE]
====
The configuration file is already set with the correct alias, `12m`, for
the 12m antenna. The `metserver` host is also properly set as `127.0.0.1`, the local host.

After copying the configuration file and before starting `telegraf` it will be necessary to set the `telegraf` user name and password in the file.
====

+
    cd ~
    wget https://github.com/nvi-inc/telegraf/releases/download/v1.14.2-vlbi-0.5.2/telegraf-vlbi_1.14.2.vlbi.0.5.2-1_amd64.deb
    dpkg -i telegraf-vlbi_1.14.2.vlbi.0.5.2-1_amd64.deb
    cp /usr2/st/telegraf/telegraf.conf /etc/telegraf
    systemctl restart telegraf

=== Testing telegraf on fs1

. Verify that there are no errors for communication with the antenna by the FS and the ACI program.
+
If there are errors, disable `telegraf` antenna access, as `root`:
+
.. Edit `/etc/telegraf.conf` and comment out the block:
+

    [[inputs.modbus_antenna]]
    ## modbus antenna controller type
    antenna_type = "intertronics12m"
    ## network address in form ip:port
    address = "12m:502"
+
.. Execute:
+

    systemctl restart telegraf


. Verify there are no other problems:

.. Check in `grafana` on the MAS to see if the antenna (if access wasn't already disabled) and met. data are updating.
+
.. A minimal test with the FS to assure that things are working would include:

+

... A quick pointing check, which should not be abnormal and should not have communication errors with the antenna.

+

... Using the `wx` command to verify met data is still available.

== fs2 installation

Once *fs1* has been successfully set-up, the *fs2* disks, running in
the spare computer, can be set-up.  Do not proceed with this step until
`telegraf` is working on *fs1*.

=== Preparing fs2

Follow the instructions in in the <<Preparing fs1>> section above, but this time doing them on *fs2*.

=== Changes needed before installing telegraf on fs2

For this part of the installation it will be necessary to take some additional steps:

. Terminate the FS on *fs1*.
. Stop `telegraf`, `metclient`, and `metserver` on *fs1*, as `root`:

    systemctl stop telegraf
    systemctl stop metclient
    systemctl stop metserver

. Move the serial connectors for the MET4A and wind sensors to the corresponding connectors on *fs2*.

. Start `metserver` on *fs2*, as `root`:

+

    systemctl start metserver

. As `oper`, start the FS on *fs2* and verify that met data is being received with the command:

+
    wx

=== Installing telegraf on fs2

Follow the directions in the <<Installing telegraf on fs1>> section above, but this time performing the steps on *fs2*.

=== Testing telegraf on fs2

Follow the directions in the <<Testing telegraf on fs1>> section above, but this time using *fs2*.

NOTE: If `telegraf` antenna access had to be disabled on *fs1* to eliminate communication errors, it is expected that this will be needed on *fs2* as well.

== Finishing up

The sections covers the steps to follow once `telegraf` has been tested successfully on _both_ *fs1* and *fs2*

=== Finalizing fs2

. Terminate the FS on *fs2*.
. Stop `telegraf` and `metserver` on *fs2*, as `root`:

    systemctl stop telegraf
    systemctl stop metserver

. Disable `telegraf` on *fs2*, as `root`:

    systemctl disable telegraf

. Follow the *successful* steps in the recoverable test procedure:

+
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing

=== Finalizing fs1

. Move the serial connectors for the MET4A and wind sensors to the original connectors on *fs1*.
. Start `metserver`, `telegraf` and `metclient` on *fs1*, as `root`:

    systemctl start metserver
    systemctl start telegraf
    systemctl start metclient

. Start the FS on *fs1*.
. Repeat the second step (Verify there are no other problems) in <<Testing telegraf on fs1>>
. If everything is still working, follow the *successful* steps in the recoverable test procedure:

+
https://nvi-inc.github.io/fsl10/raid.html#_recoverable_testing
